/* Generated by Chasm compiler — do not edit. */
#include "chasm_rl.h"

/* Extern functions */
// extern: rl_screen_width
// extern: rl_screen_height
// extern: rl_set_target_fps
// extern: rl_set_window_title
// extern: rl_fps
// extern: rl_frame_time
// extern: rl_time
// extern: rl_clear_background
// extern: rl_draw_rectangle
// extern: rl_draw_rectangle_lines
// extern: rl_draw_rectangle_rounded
// extern: rl_draw_circle
// extern: rl_draw_circle_lines
// extern: rl_draw_line
// extern: rl_draw_line_ex
// extern: rl_draw_text
// extern: rl_measure_text
// extern: rl_draw_fps
// extern: rl_load_texture
// extern: rl_unload_texture
// extern: rl_draw_texture
// extern: rl_draw_texture_ex
// extern: rl_draw_texture_rec
// extern: rl_texture_width
// extern: rl_texture_height
// extern: rl_load_font
// extern: rl_draw_text_ex
// extern: rl_init_audio
// extern: rl_close_audio
// extern: rl_load_sound
// extern: rl_play_sound
// extern: rl_stop_sound
// extern: rl_load_music
// extern: rl_play_music
// extern: rl_update_music
// extern: rl_stop_music
// extern: rl_is_key_down
// extern: rl_is_key_pressed
// extern: rl_is_key_released
// extern: rl_is_key_up
// extern: rl_get_key_pressed
// extern: rl_mouse_x
// extern: rl_mouse_y
// extern: rl_mouse_delta_x
// extern: rl_mouse_delta_y
// extern: rl_is_mouse_down
// extern: rl_is_mouse_pressed
// extern: rl_is_mouse_released
// extern: rl_mouse_wheel
// extern: rl_hide_cursor
// extern: rl_show_cursor
// extern: rl_check_collision_recs
// extern: rl_check_collision_circles
// extern: rl_check_collision_point_rec

/* Module attributes */
static double g_x;
static double g_y;
static double g_vx;
static double g_vy;
static double g_radius;
static double g_speed;

/* Attribute initialiser — call once at module load */
void chasm_module_init(ChasmCtx *ctx) {
    double t0;
    double t1;
    double t2;
    double t3;
    double t4;
    double t5;

    t0 = 400;
    t1 = 300;
    t2 = 200;
    t3 = 150;
    t4 = 24;
    t5 = 1;
    g_x = t0;
    g_y = t1;
    g_vx = t2;
    g_vy = t3;
    g_radius = t4;
    g_speed = t5;
}

/* Forward declarations */
void chasm_on_tick(ChasmCtx *ctx, double t0);
void chasm_on_draw(ChasmCtx *ctx);

void chasm_on_tick(ChasmCtx *ctx, double t0) {
    double t1;
    int64_t t2;
    bool t3;
    double t4;
    int64_t t5;
    bool t6;
    double t7;
    double t8;
    double t9;
    double t10;
    double t11;
    double t12;
    double t13;
    double t14;
    double t15;
    double t16;
    double t17;
    double t18;
    double t19;
    bool t20;
    double t21;
    double t22;
    double t23;
    double t24;
    double t25;
    double t26;
    double t27;
    bool t28;
    double t29;
    double t30;
    double t31;
    double t32;
    double t33;
    double t34;
    double t35;
    double t36;
    double t37;
    bool t38;
    double t39;
    double t40;
    double t41;
    double t42;
    double t43;
    double t44;
    double t45;
    bool t46;
    double t47;
    double t48;
    double t49;
    double t50;
    double t51;
    double t52;
    double t53;

    t1 = 1;
    g_speed = t1;
    t2 = 340;
    t3 = rl_is_key_down(t2);
    if (t3) goto L0; else goto L1;
L0:;
    t4 = 0.3;
    g_speed = t4;
    goto L2;
L1:;
    goto L2;
L2:;
    t5 = 32;
    t6 = rl_is_key_down(t5);
    if (t6) goto L3; else goto L4;
L3:;
    t7 = 5.5;
    g_speed = t7;
    goto L5;
L4:;
    goto L5;
L5:;
    t8 = g_speed;
    t9 = t0 * t8;
    t10 = g_x;
    t11 = g_vx;
    t12 = t11 * t9;
    t13 = t10 + t12;
    g_x = t13;
    t14 = g_y;
    t15 = g_vy;
    t16 = t15 * t9;
    t17 = t14 + t16;
    g_y = t17;
    t18 = g_x;
    t19 = g_radius;
    t20 = t18 < t19;
    if (t20) goto L6; else goto L7;
L6:;
    t21 = g_radius;
    g_x = t21;
    t22 = g_vx;
    t23 = chasm_abs(ctx, t22);
    g_vx = t23;
    goto L8;
L7:;
    goto L8;
L8:;
    t24 = g_x;
    t25 = 800;
    t26 = g_radius;
    t27 = t25 - t26;
    t28 = t24 > t27;
    if (t28) goto L9; else goto L10;
L9:;
    t29 = 800;
    t30 = g_radius;
    t31 = t29 - t30;
    g_x = t31;
    t32 = 0;
    t33 = g_vx;
    t34 = chasm_abs(ctx, t33);
    t35 = t32 - t34;
    g_vx = t35;
    goto L11;
L10:;
    goto L11;
L11:;
    t36 = g_y;
    t37 = g_radius;
    t38 = t36 < t37;
    if (t38) goto L12; else goto L13;
L12:;
    t39 = g_radius;
    g_y = t39;
    t40 = g_vy;
    t41 = chasm_abs(ctx, t40);
    g_vy = t41;
    goto L14;
L13:;
    goto L14;
L14:;
    t42 = g_y;
    t43 = 600;
    t44 = g_radius;
    t45 = t43 - t44;
    t46 = t42 > t45;
    if (t46) goto L15; else goto L16;
L15:;
    t47 = 600;
    t48 = g_radius;
    t49 = t47 - t48;
    g_y = t49;
    t50 = 0;
    t51 = g_vy;
    t52 = chasm_abs(ctx, t51);
    t53 = t50 - t52;
    g_vy = t53;
    goto L17;
L16:;
    goto L17;
L17:;
    return;
}

void chasm_on_draw(ChasmCtx *ctx) {
    int64_t t0;
    double t1;
    double t2;
    double t3;
    double t4;
    double t5;
    int64_t t6;
    double t7;
    double t8;
    double t9;
    int64_t t10;
    const char* t11;
    double t12;
    double t13;
    int64_t t14;
    int64_t t15;
    const char* t16;
    double t17;
    double t18;
    int64_t t19;
    int64_t t20;
    double t21;
    double t22;

    t0 = 404234495;
    rl_clear_background(t0);
    t1 = g_x;
    t2 = g_y;
    t3 = g_radius;
    t4 = 6;
    t5 = t3 + t4;
    t6 = 4282668339;
    rl_draw_circle_lines(t1, t2, t5, t6);
    t7 = g_x;
    t8 = g_y;
    t9 = g_radius;
    t10 = 4282668543;
    rl_draw_circle(t7, t8, t9, t10);
    t11 = "Chasm + Raylib 5.5";
    t12 = 12;
    t13 = 12;
    t14 = 20;
    t15 = 4294967295;
    rl_draw_text(t11, t12, t13, t14, t15);
    t16 = "SHIFT: slow  |  SPACE: boost";
    t17 = 12;
    t18 = 38;
    t19 = 16;
    t20 = 2290649343;
    rl_draw_text(t16, t17, t18, t19, t20);
    t21 = 12;
    t22 = 580;
    rl_draw_fps(t21, t22);
    return;
}

/* Hot-reload migration — call this after dlopen'ing the new module.
 * The host engine must preserve ChasmCtx across the swap.
 * Frame state is always discarded (cleared each tick).
 * *   @x: preserved
 *   @y: preserved
 *   @vx: preserved
 *   @vy: preserved
 *   @radius: preserved
 *   @speed: preserved
 */
void chasm_reload_migrate(ChasmCtx *ctx) {
    chasm_clear_frame(ctx);}

