/* Generated by Chasm compiler — do not edit. */
#include "chasm_rt.h"

/* Struct types */
typedef struct {
    const char* kind;
    const char* value;
} Token;

/* Typed array helpers */
static inline Token chasm_array_get_Token(ChasmCtx *ctx, ChasmArray *a, int64_t i) {
    (void)ctx;
    static const Token zero = {0};
    if (i < 0 || i >= a->len) return zero;
    return ((Token*)a->data)[i];
}
static inline void chasm_array_set_Token(ChasmCtx *ctx, ChasmArray *a, int64_t i, Token v) {
    (void)ctx;
    if (i >= 0 && i < a->len) ((Token*)a->data)[i] = v;
}
static inline void chasm_array_push_Token(ChasmCtx *ctx, ChasmArray *a, Token v) {
    (void)ctx;
    if (a->len >= a->cap) {
        a->cap = a->cap * 2 + 8;
        a->data = realloc(a->data, (size_t)a->cap * sizeof(Token));
    }
    if (a->data) ((Token*)a->data)[a->len++] = v;
}

/* Attribute initialiser — call once at module load */
void chasm_module_init(ChasmCtx *ctx) {
    (void)ctx;
}

/* Forward declarations */
ChasmArray chasm_make_tokens(ChasmCtx *ctx, const char* t0);
void chasm_main(ChasmCtx *ctx);

ChasmArray chasm_make_tokens(ChasmCtx *ctx, const char* t0) {
    int64_t t1;
    ChasmArray t2;
    int64_t t3;
    int64_t t4;
    bool t5;
    int64_t t6;
    int64_t t7;
    bool t8;
    int64_t t9;
    int64_t t10;
    bool t11;
    int64_t t12;
    int64_t t13;
    bool t14;
    bool t15;
    int64_t t16;
    int64_t t17;
    const char* t18;
    Token t19;
    const char* t20;

    t1 = 0;
    t2 = chasm_array_new(ctx, t1);
    t3 = 0;
    t4 = chasm_str_len(ctx, t0);
    goto L0;
L0:;
    t5 = t3 < t4;
    if (t5) goto L1; else goto L2;
L1:;
    t6 = chasm_str_char_at(ctx, t0, t3);
    t7 = 32;
    t8 = t6 == t7;
    if (t8) goto L3; else goto L4;
L3:;
    t9 = 1;
    t10 = t3 + t9;
    t3 = t10;
    goto L5;
L4:;
    goto L6;
L6:;
    t11 = t3 < t4;
    t12 = chasm_str_char_at(ctx, t0, t3);
    t13 = 32;
    t14 = t12 != t13;
    t15 = t11 && t14;
    if (t15) goto L7; else goto L8;
L7:;
    t16 = 1;
    t17 = t3 + t16;
    t3 = t17;
    goto L6;
L8:;
    t18 = chasm_str_slice(ctx, t0, t3, t3);
    t20 = "word";
    t19.kind = t20;
    t19.value = t18;
    chasm_array_push_Token(ctx, &t2, t19);
    goto L5;
L5:;
    goto L0;
L2:;
    return t2;
}

void chasm_main(ChasmCtx *ctx) {
    const char* t0;
    ChasmArray t1;
    int64_t t2;
    int64_t t3;
    Token t4;
    const char* t5;
    int64_t t6;
    Token t7;
    const char* t8;

    t0 = "hello world foo";
    t1 = chasm_make_tokens(ctx, t0);
    t2 = chasm_array_len(ctx, &t1);
    chasm_print(ctx, t2);
    t3 = 0;
    t4 = chasm_array_get_Token(ctx, &t1, t3);
    t5 = t4.value;
    chasm_print_s(ctx, t5);
    t6 = 1;
    t7 = chasm_array_get_Token(ctx, &t1, t6);
    t8 = t7.value;
    chasm_print_s(ctx, t8);
    return;
}

/* Hot-reload migration — call this after dlopen'ing the new module.
 * The host engine must preserve ChasmCtx across the swap.
 * Frame state is always discarded (cleared each tick).
 * */
void chasm_reload_migrate(ChasmCtx *ctx) {
    chasm_clear_frame(ctx);}

