/* Generated by Chasm compiler — do not edit. */
#include "chasm_rt.h"

/* Struct types */
typedef struct {
    int64_t x;
    int64_t y;
} Vec2;

typedef struct {
    int64_t health;
    Vec2 pos;
} Player;

/* Typed array helpers */
static inline Vec2 chasm_array_get_Vec2(ChasmCtx *ctx, ChasmArray *a, int64_t i) {
    (void)ctx;
    static const Vec2 zero = {0};
    if (i < 0 || i >= a->len) return zero;
    return ((Vec2*)a->data)[i];
}
static inline void chasm_array_set_Vec2(ChasmCtx *ctx, ChasmArray *a, int64_t i, Vec2 v) {
    (void)ctx;
    if (i >= 0 && i < a->len) ((Vec2*)a->data)[i] = v;
}
static inline void chasm_array_push_Vec2(ChasmCtx *ctx, ChasmArray *a, Vec2 v) {
    (void)ctx;
    if (a->len >= a->cap) {
        a->cap = a->cap * 2 + 8;
        a->data = realloc(a->data, (size_t)a->cap * sizeof(Vec2));
    }
    if (a->data) ((Vec2*)a->data)[a->len++] = v;
}
static inline Player chasm_array_get_Player(ChasmCtx *ctx, ChasmArray *a, int64_t i) {
    (void)ctx;
    static const Player zero = {0};
    if (i < 0 || i >= a->len) return zero;
    return ((Player*)a->data)[i];
}
static inline void chasm_array_set_Player(ChasmCtx *ctx, ChasmArray *a, int64_t i, Player v) {
    (void)ctx;
    if (i >= 0 && i < a->len) ((Player*)a->data)[i] = v;
}
static inline void chasm_array_push_Player(ChasmCtx *ctx, ChasmArray *a, Player v) {
    (void)ctx;
    if (a->len >= a->cap) {
        a->cap = a->cap * 2 + 8;
        a->data = realloc(a->data, (size_t)a->cap * sizeof(Player));
    }
    if (a->data) ((Player*)a->data)[a->len++] = v;
}

/* Module attributes */
static int64_t g_score;
static int64_t g_high_score;

/* Attribute initialiser — call once at module load */
void chasm_module_init(ChasmCtx *ctx) {
    int64_t t0;
    int64_t t1;

    t0 = 0;
    t1 = 0;
    g_score = t0;
    g_high_score = t1;
}

/* Forward declarations */
void chasm_compute_delta(ChasmCtx *ctx, int64_t t0);
void chasm_on_tick(ChasmCtx *ctx, int64_t t0);
void chasm_on_save(ChasmCtx *ctx);
void chasm_describe_status(ChasmCtx *ctx, const char* t0);
void chasm_run_loop(ChasmCtx *ctx, int64_t t0);

void chasm_compute_delta(ChasmCtx *ctx, int64_t t0) {
    double t1;
    double t2;

    t1 = 9.8;
    t2 = t1 * t0;
    return;
}

void chasm_on_tick(ChasmCtx *ctx, int64_t t0) {
    int64_t t1;
    int64_t t2;
    double t3;
    double t4;
    double t5;
    double t6;
    double t7;
    double t8;
    double t9;
    bool t10;
    double t11;
    double t12;
    double t13;

    t1 = chasm_compute_delta(ctx, t0);
    t2 = chasm_promote_scalar(t1); /* frame -> script */
    g_score = t2;
    t3 = 2;
    t4 = chasm_scale(ctx, t1, t3);
    t5 = 0;
    t6 = 100;
    t7 = chasm_clamp(ctx, t4, t5, t6);
    t8 = t7;
    t9 = 50;
    t10 = t8 > t9;
    if (t10) goto L0; else goto L1;
L0:;
    t11 = chasm_promote_scalar(t8); /* frame -> script */
    g_score = t11;
    goto L2;
L1:;
    t12 = 0;
    t13 = chasm_promote_scalar(t12); /* frame -> script */
    g_score = t13;
    goto L2;
L2:;
    return;
}

void chasm_on_save(ChasmCtx *ctx) {
    int64_t t0;
    int64_t t1;

    t0 = g_score;
    t1 = chasm_promote_scalar(t0); /* script -> persistent */
    g_high_score = t1;
    return;
}

void chasm_describe_status(ChasmCtx *ctx, const char* t0) {
    int64_t t1;
    const char* t2;
    bool t3;
    const char* t4;
    const char* t5;
    bool t6;
    const char* t7;
    const char* t8;
    bool t9;
    const char* t10;
    bool t11;
    const char* t12;

    t2 = "idle";
    t3 = (t0 && t2) ? (strcmp(t0, t2) == 0) : (t0 == t2);
    if (t3) goto L1; else goto L2;
L1:;
    t4 = "standing by";
    t1 = t4;
    goto L0;
L2:;
    t5 = "running";
    t6 = (t0 && t5) ? (strcmp(t0, t5) == 0) : (t0 == t5);
    if (t6) goto L3; else goto L4;
L3:;
    t7 = "in motion";
    t1 = t7;
    goto L0;
L4:;
    t8 = "dead";
    t9 = (t0 && t8) ? (strcmp(t0, t8) == 0) : (t0 == t8);
    if (t9) goto L5; else goto L6;
L5:;
    t10 = "game over";
    t1 = t10;
    goto L0;
L6:;
    t11 = true;
    if (t11) goto L7; else goto L8;
L7:;
    t12 = "unknown";
    t1 = t12;
    goto L0;
L8:;
L0:;
    return;
}

void chasm_run_loop(ChasmCtx *ctx, int64_t t0) {
    int64_t t1;
    bool t2;
    int64_t t3;
    int64_t t4;

    t1 = 0;
    goto L0;
L0:;
    t2 = t1 < t0;
    if (t2) goto L1; else goto L2;
L1:;
    t3 = 1;
    t4 = t1 + t3;
    t1 = t4;
    goto L0;
L2:;
    return;
}

/* Hot-reload migration — call this after dlopen'ing the new module.
 * The host engine must preserve ChasmCtx across the swap.
 * Frame state is always discarded (cleared each tick).
 * *   @score: preserved
 *   @high_score: preserved
 */
void chasm_reload_migrate(ChasmCtx *ctx) {
    chasm_clear_frame(ctx);}

