/* Generated by Chasm bootstrap compiler - do not edit. */
#include "chasm_rt.h"

/* Enum types */
typedef enum {
  State_Idle = 0,
  State_Running = 1,
  State_Jumping = 2,
  State_Dead = 3
} State_Tag;

typedef State_Tag State;

typedef enum {
  Dir_North = 0,
  Dir_South = 1,
  Dir_East = 2,
  Dir_West = 3
} Dir_Tag;

typedef Dir_Tag Dir;

typedef enum {
  Shape_Circle = 0,
  Shape_Rect = 1,
  Shape_Point = 2
} Shape_Tag;

typedef struct {
  Shape_Tag tag;
  union {
    struct { float v; } Circle;
    struct { float,float v; } Rect;
  };
} Shape;

#define Shape_make_Circle(val) (Shape){ .tag = Shape_Circle, .Circle.v = (val) }
#define Shape_make_Rect(val) (Shape){ .tag = Shape_Rect, .Rect.v = (val) }

/* Forward declarations */
double chasm_dx(ChasmCtx *ctx, Dir);
double chasm_dy(ChasmCtx *ctx, Dir);
const char* chasm_tier(ChasmCtx *ctx, int64_t);
int64_t chasm_color_for(ChasmCtx *ctx, const char*);

/* Module attributes */
static State g_state;

void chasm_module_init(ChasmCtx *ctx) {
  g_state = State_Idle;
}

double chasm_dx(ChasmCtx *ctx, Dir d) {
  return ((strcmp(d, "East") == 0) ? 1.0 : ((strcmp(d, "West") == 0) ? -(1.0) : 0.0));
}

double chasm_dy(ChasmCtx *ctx, Dir d) {
  return ((strcmp(d, "South") == 0) ? 1.0 : ((strcmp(d, "North") == 0) ? -(1.0) : 0.0));
}

const char* chasm_tier(ChasmCtx *ctx, int64_t score) {
  return (((score / 100) == 0) ? "bronze" : (((score / 100) == 1) ? "silver" : (((score / 100) == 2) ? "gold" : "legend")));
}

int64_t chasm_color_for(ChasmCtx *ctx, const char* s) {
  return ((strcmp(s, "healthy") == 0) ? 0x00ff00ff : ((strcmp(s, "hurt") == 0) ? 0xff8800ff : ((strcmp(s, "critical") == 0) ? 0xff0000ff : 0xffffffff)));
}

void chasm_main(ChasmCtx *ctx) {
  if (g_state == State_Idle) {
    chasm_print_s(ctx, "waiting");
  }
  chasm_print_f(ctx, chasm_dx(ctx, Dir_East));
  chasm_print_f(ctx, chasm_dx(ctx, Dir_North));
  chasm_print_f(ctx, chasm_dy(ctx, Dir_South));
  chasm_print_f(ctx, chasm_dy(ctx, Dir_West));
  chasm_print_s(ctx, chasm_tier(ctx, 50));
  chasm_print_s(ctx, chasm_tier(ctx, 150));
  chasm_print_s(ctx, chasm_tier(ctx, 250));
  chasm_print_s(ctx, chasm_tier(ctx, 999));
  chasm_print(ctx, chasm_color_for(ctx, "healthy"));
  chasm_print(ctx, chasm_color_for(ctx, "unknown"));
}

